Repository boostcamp-2020/IssueTracker-05, pull requests merged in 2020-10, with the labels that each got.

#105 feat: 최초 커밋 closed #104
  .DS_Store
  .gitignore
  IssueTracker.xcodeproj/project.pbxproj
  IssueTracker.xcworkspace/contents.xcworkspacedata
  IssueTracker/IssueTracker.xcodeproj/project.pbxproj
  IssueTracker/IssueTracker.xcodeproj/project.xcworkspace/contents.xcworkspacedata
  IssueTracker/IssueTracker.xcodeproj/project.xcworkspace/xcshareddata/IDEWorkspaceChecks.plist
  IssueTracker/IssueTracker/AppDelegate.swift
  IssueTracker/IssueTracker/Assets.xcassets/AppIcon.appiconset/Contents.json
  IssueTracker/IssueTracker/Assets.xcassets/Contents.json
  IssueTracker/IssueTracker/Base.lproj/LaunchScreen.storyboard
  IssueTracker/IssueTracker/Base.lproj/Main.storyboard
  IssueTracker/IssueTracker/Info.plist
  IssueTracker/IssueTracker/SceneDelegate.swift
  IssueTracker/IssueTracker/ViewController.swift
  Podfile
  Podfile.lock
Labels: iOS

#109 chore : 프론트 작업 삭제
  client/.gitignore
  client/README.md
  client/package-lock.json
  client/package.json
  client/public/favicon.ico
  client/public/index.html
  client/public/logo192.png
  client/public/logo512.png
  client/public/manifest.json
  client/public/robots.txt
  client/src/App.css
  client/src/App.js
  client/src/App.test.js
  client/src/index.css
  client/src/index.js
  client/src/logo.svg
  client/src/reportWebVitals.js
  client/src/setupTests.js
Labels: backend

#108 chore : 백엔드 개발환경 삭제
  server/.env.example
  server/.eslintrc.json
  server/.gitignore
  server/.prettierrc
  server/babel.config.json
  server/nodemon.json
  server/package-lock.json
  server/package.json
  server/src/api/controllers/login.js
  server/src/api/index.js
  server/src/api/routes/login.js
  server/src/app.js
  server/src/config/config.json
  server/src/config/express.js
  server/src/config/server.js
  server/src/loaders/express.js
  server/src/loaders/index.js
  server/src/migrations/.keep
  server/src/models/index.js
  server/src/seeders/.keep
  server/webpack.config.js
Labels: frontend

#115 [BE #111~#114] DB 설계
  server/.env.example
  server/package-lock.json
  server/package.json
  server/src/config/config.json
  server/src/config/dbConfig.js
  server/src/loaders/index.js
  server/src/loaders/mysql.js
  server/src/models/comment.js
  server/src/models/index.js
  server/src/models/issue.js
  server/src/models/label.js
  server/src/models/milestone.js
  server/src/models/user.js
Labels: backend, chore

#117 [BE] 개발환경 설정 및 DB 설계
  README.md
  server/.env.example
  server/.eslintrc.json
  server/.gitignore
  server/.prettierrc
  server/babel.config.json
  server/nodemon.json
  server/package-lock.json
  server/package.json
  server/src/api/controllers/login.js
  server/src/api/index.js
  server/src/api/routes/login.js
  server/src/app.js
  server/src/config/dbConfig.js
  server/src/config/express.js
  server/src/config/server.js
  server/src/loaders/express.js
  server/src/loaders/index.js
  server/src/loaders/mysql.js
  server/src/migrations/.keep
  server/src/models/comment.js
  server/src/models/index.js
  server/src/models/issue.js
  server/src/models/label.js
  server/src/models/milestone.js
  server/src/models/user.js
  server/src/seeders/.keep
  server/webpack.config.js
Labels: backend, chore

#121 집에 와서 추가적으로 작업한 내용
  iOS/IssueTracker/IssueTracker.xcodeproj/project.pbxproj
  iOS/IssueTracker/IssueTracker/Base.lproj/Main.storyboard
  iOS/IssueTracker/IssueTracker/IssueList/IssueListMainViewController.swift
  iOS/IssueTracker/IssueTracker/IssueList/Model/IssueListModel.swift
  iOS/IssueTracker/IssueTracker/IssueList/View/Main/IssueListMainViewController.swift
  iOS/IssueTracker/IssueTracker/IssueList/View/Main/IssueResultCellView.swift
  iOS/IssueTracker/IssueTracker/IssueList/View/Main/IssueResultViewController.swift
  iOS/IssueTracker/IssueTracker/IssueList/View/Main/SearchListCellView.swift
  iOS/IssueTracker/IssueTracker/IssueList/View/Main/SearchListViewController.swift
  iOS/IssueTracker/IssueTracker/IssueList/ViewModel/IssueListViewModel.swift
  iOS/IssueTracker/Podfile.lock
Labels: iOS

#124 Feature/issue list view model
  iOS/IssueTracker/IssueTracker.xcodeproj/project.pbxproj
  iOS/IssueTracker/IssueTracker/Base.lproj/Main.storyboard
  iOS/IssueTracker/IssueTracker/IssueList/IssueListViewController.swift
  iOS/IssueTracker/IssueTracker/IssueList/View/IssueList.storyboard
  iOS/IssueTracker/IssueTracker/IssueList/View/Main/IssueListMainViewController.swift
  iOS/IssueTracker/IssueTracker/IssueList/ViewModel/IssueListViewModel.swift
Labels: enhancement, iOS

#125 첫번째 화면 설정
  .gitignore
  iOS/IssueTracker/IssueTracker.xcodeproj/project.pbxproj
  iOS/IssueTracker/IssueTracker/Common/SceneDelegate.swift
  iOS/IssueTracker/IssueTracker/dummyToken.txt
Labels: chore, iOS

#126 [BE #23 #30 #33] 로컬 회원가입 설정 및 테스트 코드 작성, Alias 설정
  server/.eslintrc.json
  server/babel.config.json
  server/package-lock.json
  server/package.json
  server/src/api/controllers/signup.js
  server/src/api/index.js
  server/src/api/middlewares/signup.js
  server/src/api/routes/login.js
  server/src/api/routes/signup.js
  server/src/app.js
  server/src/config/bcrypt.js
  server/src/loaders/express.js
  server/src/models/index.js
  server/src/services/passwordBcrypt.js
  server/src/services/signup.js
  server/tests/test.http
Labels: backend, chore, style

#127 [BE #28 #29] 로그인 - Passport Local 기능 구현
  server/.env.example
  server/src/api/controllers/login.js
  server/src/api/routes/login.js
  server/src/config/passport.js
  server/src/loaders/express.js
  server/src/loaders/passport/index.js
  server/src/loaders/passport/jwt.js
  server/src/loaders/passport/local.js
  server/src/services/passport.js
  server/tests/test.http
Labels: backend, enhancement

#128 [iOS #36, #54] SearchView<->ResultList 전환 수정
  iOS/IssueTracker/IssueTracker/IssueList/View/IssueList.storyboard
  iOS/IssueTracker/IssueTracker/IssueList/View/Main/IssueListMainViewController.swift
  iOS/IssueTracker/IssueTracker/IssueList/View/Main/SearchListViewController.swift
Labels: enhancement, iOS

#131 [BE #4] Github OAuth 구성 - 미완성
  server/package-lock.json
  server/package.json
  server/src/api/controllers/login.js
  server/src/api/routes/login.js
  server/src/loaders/passport/github.js
  server/src/loaders/passport/index.js
  server/tests/github.html
  server/tests/test.http
Labels: backend, bug

#130 [iOS #11] 탭바 컨트롤러 첫 화면 설정
  iOS/IssueTracker/IssueTracker.xcodeproj/project.pbxproj
  iOS/IssueTracker/IssueTracker/Common/SceneDelegate.swift
  iOS/IssueTracker/IssueTracker/LabelList/LabelList.storyboard
  iOS/IssueTracker/IssueTracker/LabelList/LabelListViewController.swift
  iOS/IssueTracker/IssueTracker/MilestoneList/MilestoneList.storyboard
  iOS/IssueTracker/IssueTracker/MilestoneList/MilestoneListViewController.swift
Labels: enhancement, iOS

#132 [iOS #12] Login With Apple
  iOS/IssueTracker/IssueTracker.xcodeproj/project.pbxproj
  iOS/IssueTracker/IssueTracker/Info.plist
  iOS/IssueTracker/IssueTracker/IssueTracker.entitlements
  iOS/IssueTracker/IssueTracker/LogIn/Model/LoginManager.swift
  iOS/IssueTracker/IssueTracker/LogIn/View/SingIn/Login.storyboard
  iOS/IssueTracker/IssueTracker/LogIn/View/SingIn/SignInViewController.swift
Labels: enhancement, iOS
