Repository boostcamp-2020/IssueTracker-05, pull requests merged in 2020-11, with the labels that each got.

#133 [BE #4] Github OAuth 오류 수정, Github 설정 env화
  server/.env.example
  server/src/api/controllers/login.js
  server/src/api/routes/login.js
  server/src/config/passport.js
  server/src/loaders/mysql.js
  server/src/loaders/passport/github.js
  server/src/services/passport.js
Labels: backend, chore

#134 [FE #no] 개발환경 수정 CRA -> init
  client/.babelrc
  client/.gitignore
  client/README.md
  client/package-lock.json
  client/package.json
  client/public/favicon.ico
  client/public/index.html
  client/public/logo192.png
  client/public/logo512.png
  client/public/manifest.json
  client/public/robots.txt
  client/src/App.css
  client/src/App.js
  client/src/App.test.js
  client/src/HelloWorld.js
  client/src/index.css
  client/src/index.html
  client/src/index.js
  client/src/logo.svg
  client/src/reportWebVitals.js
  client/src/setupTests.js
  client/webpack.config.js
Labels: chore, frontend

#142 [BE #3 #6 #14 #22 #24 #31] Milestone 백엔드 구성, 데이터베이스 수정, 테스트코드 작성
  server/.eslintrc.json
  server/src/api/controllers/login.js
  server/src/api/controllers/milestone.js
  server/src/api/index.js
  server/src/api/routes/login.js
  server/src/api/routes/milestone.js
  server/src/models/comment.js
  server/src/models/issue.js
  server/src/models/milestone.js
  server/src/models/user.js
  server/src/services/milestone.js
  server/src/services/passport.js
  server/tests/milestone.http
Labels: backend, enhancement, style

#144 [BE #42 #43 #46 #47 #58 #131] label과 comment 백엔드 구성, 테스트코드 작성
  server/src/api/controllers/comment.js
  server/src/api/controllers/label.js
  server/src/api/routes/comment.js
  server/src/api/routes/label.js
  server/src/services/comment.js
  server/src/services/label.js
  server/tests/comment.http
  server/tests/label.http
Labels: backend, enhancement

#145 [BE] feat: merge 병합
  server/src/api/index.js
Labels: backend, chore

#146 [iOS #137,#138] 개발 환경 재설정
  iOS/IssueTracker/IssueTracker.xcodeproj/project.pbxproj
  iOS/IssueTracker/IssueTracker/Common/SceneDelegate.swift
  iOS/IssueTracker/IssueTracker/IssueList/Model/IssueListModel.swift
  iOS/IssueTracker/IssueTracker/IssueList/View/Main/IssueListMainViewController.swift
  iOS/IssueTracker/IssueTracker/IssueList/View/Main/IssueResultViewController.swift
  iOS/IssueTracker/IssueTracker/IssueList/View/Main/SearchListViewController.swift
  iOS/IssueTracker/IssueTracker/IssueList/ViewModel/IssueListViewModel.swift
  iOS/IssueTracker/IssueTracker/IssueList/ViewModel/SearchListViewModel.swift
  iOS/IssueTracker/IssueTracker/LogIn/View/SingIn/SignInViewController.swift
  iOS/IssueTracker/Podfile
  iOS/IssueTracker/Podfile.lock
Labels: bug, chore, iOS

#147 [BE #56] 특정 이슈 read API 구현
  server/src/api/controllers/issue.js
  server/src/api/index.js
  server/src/api/routes/issue.js
  server/src/services/issue.js
  server/tests/issue.http
Labels: backend

#148 [BE #58] 원하는 이슈의 댓글 전체를 불러오는 기능 추가, 테스트 코드 작성
  server/src/api/controllers/comment.js
  server/src/api/middlewares/passportJwt.js
  server/src/api/routes/comment.js
  server/src/services/comment.js
  server/tests/comment.http
Labels: backend, enhancement

#149 [iOS #50, #61] cell UI 변경
  iOS/IssueTracker/IssueTracker/Common/SceneDelegate.swift
  iOS/IssueTracker/IssueTracker/IssueList/View/IssueList.storyboard
  iOS/IssueTracker/IssueTracker/IssueList/View/Main/IssueListMainViewController.swift
  iOS/IssueTracker/IssueTracker/IssueList/View/Main/IssueResultCellView.swift
  iOS/IssueTracker/IssueTracker/IssueList/View/Main/IssueResultViewController.swift
Labels: enhancement, iOS

#152 [BE #40 #56] 애플 Oauth, 이슈 추가기능 구현, 테스트 코드 작성
  server/src/api/controllers/issue.js
  server/src/api/controllers/label.js
  server/src/api/controllers/login.js
  server/src/api/middlewares/comment.js
  server/src/api/middlewares/signup.js
  server/src/api/routes/comment.js
  server/src/api/routes/issue.js
  server/src/api/routes/signup.js
  server/src/app.js
  server/src/config/passport.js
  server/src/loaders/passport/github.js
  server/src/loaders/passport/jwt.js
  server/src/models/index.js
  server/src/models/issue.js
  server/src/services/comment.js
  server/src/services/issue.js
  server/src/services/label.js
  server/src/services/passport.js
  server/tests/auth.http
  server/tests/comment.http
  server/tests/issue.http
  server/tests/label.http
Labels: backend, bug, enhancement

#153 [iOS #57]cell 스와이핑으로 delete, close 버튼 표시 기능 추가
  .gitignore
  iOS/IssueTracker/IssueTracker.xcodeproj/project.pbxproj
  iOS/IssueTracker/IssueTracker.xcodeproj/project.xcworkspace/contents.xcworkspacedata
  iOS/IssueTracker/IssueTracker.xcodeproj/project.xcworkspace/xcshareddata/IDEWorkspaceChecks.plist
  iOS/IssueTracker/IssueTracker.xcworkspace/contents.xcworkspacedata
  iOS/IssueTracker/IssueTracker.xcworkspace/xcshareddata/IDEWorkspaceChecks.plist
  iOS/IssueTracker/IssueTracker.xcworkspace/xcshareddata/swiftpm/Package.resolved
  iOS/IssueTracker/IssueTracker/Assets.xcassets/AppIcon.appiconset/Contents.json
  iOS/IssueTracker/IssueTracker/Assets.xcassets/Contents.json
  iOS/IssueTracker/IssueTracker/Base.lproj/LaunchScreen.storyboard
  iOS/IssueTracker/IssueTracker/Base.lproj/Main.storyboard
  iOS/IssueTracker/IssueTracker/Common/AppDelegate.swift
  iOS/IssueTracker/IssueTracker/Common/Bindable.swift
  iOS/IssueTracker/IssueTracker/Common/SceneDelegate.swift
  iOS/IssueTracker/IssueTracker/Extenstion/UIVIew+LivePreview.swift
  iOS/IssueTracker/IssueTracker/Info.plist
  iOS/IssueTracker/IssueTracker/IssueList/Model/IssueListModel.swift
  iOS/IssueTracker/IssueTracker/IssueList/View/IssueList.storyboard
  iOS/IssueTracker/IssueTracker/IssueList/View/Main/IssueListMainViewController.swift
  iOS/IssueTracker/IssueTracker/IssueList/View/Main/IssueResultList/BothSidesSwipingView.swift
  iOS/IssueTracker/IssueTracker/IssueList/View/Main/IssueResultList/IssueDetailedView.swift
  iOS/IssueTracker/IssueTracker/IssueList/View/Main/IssueResultList/IssueResultCellView.swift
  iOS/IssueTracker/IssueTracker/IssueList/View/Main/IssueResultList/IssueResultViewController.swift
  iOS/IssueTracker/IssueTracker/IssueList/View/Main/SearchList/SearchListCellView.swift
  iOS/IssueTracker/IssueTracker/IssueList/View/Main/SearchList/SearchListViewController.swift
  iOS/IssueTracker/IssueTracker/IssueList/ViewModel/IssueListViewModel.swift
  iOS/IssueTracker/IssueTracker/IssueList/ViewModel/SearchListViewModel.swift
  iOS/IssueTracker/IssueTracker/IssueTracker.entitlements
  iOS/IssueTracker/IssueTracker/LabelList/LabelList.storyboard
  iOS/IssueTracker/IssueTracker/LabelList/LabelListViewController.swift
  iOS/IssueTracker/IssueTracker/LogIn/Model/LoginManager.swift
  iOS/IssueTracker/IssueTracker/LogIn/Model/LoginModel.swift
  iOS/IssueTracker/IssueTracker/LogIn/Model/ValidationChecker.swift
  iOS/IssueTracker/IssueTracker/LogIn/View/SignUp/SignUp.storyboard
  iOS/IssueTracker/IssueTracker/LogIn/View/SignUp/SignUpViewController.swift
  iOS/IssueTracker/IssueTracker/LogIn/View/SingIn/ErrorMessageLabel.swift
  iOS/IssueTracker/IssueTracker/LogIn/View/SingIn/Login.storyboard
  iOS/IssueTracker/IssueTracker/LogIn/View/SingIn/SignInViewController.swift
  iOS/IssueTracker/IssueTracker/LogIn/ViewModel/SignInViewModel.swift
  iOS/IssueTracker/IssueTracker/MilestoneList/MilestoneList.storyboard
  iOS/IssueTracker/IssueTracker/MilestoneList/MilestoneListModel.swift
  iOS/IssueTracker/IssueTracker/MilestoneList/MilestoneListViewCell.swift
  iOS/IssueTracker/IssueTracker/MilestoneList/MilestoneListViewController.swift
  iOS/IssueTracker/IssueTracker/dummy.json
  iOS/IssueTracker/Podfile
  iOS/IssueTracker/Podfile.lock
Labels: enhancement, iOS

#154 [BE #62, #64, #67] 이슈 상세 내용 수정 API
  server/src/api/controllers/issue.js
  server/src/api/routes/issue.js
  server/src/services/issue.js
  server/tests/issue.http
Labels: backend, enhancement

#156 [BE #05] Apple 설정 완료, 이미지 업로드 추가, 필터링 기능 작성 중
  server/.env.example
  server/package-lock.json
  server/package.json
  server/src/api/controllers/image.js
  server/src/api/controllers/issueFilter.js
  server/src/api/index.js
  server/src/api/middlewares/signup.js
  server/src/api/routes/image.js
  server/src/api/routes/issueFilter.js
  server/src/api/routes/login.js
  server/src/config/passport.js
  server/src/loaders/passport/apple.js
  server/src/loaders/passport/github.js
  server/src/loaders/passport/index.js
  server/src/services/issue.js
  server/src/services/issueFilter.js
  server/src/services/searchFilter.js
  server/tests/imgur.html
  server/tests/issueFilter.http
Labels: backend

#157 [BE #41] User 호출 API 구현
  server/src/api/controllers/user.js
  server/src/api/index.js
  server/src/api/routes/user.js
  server/src/services/user.js
  server/tests/user.http
Labels: backend, enhancement

#155 [iOS #7, #8] 회원 가입 및 로그인 기능 추가
  iOS/IssueTracker/IssueTracker.xcodeproj/project.pbxproj
  iOS/IssueTracker/IssueTracker/Common/AppDelegate.swift
  iOS/IssueTracker/IssueTracker/Common/SceneDelegate.swift
  iOS/IssueTracker/IssueTracker/Extenstion/UIButton.swift
  iOS/IssueTracker/IssueTracker/Extenstion/UITextField+LeftView.swift
  iOS/IssueTracker/IssueTracker/LogIn/Model/LoginManager.swift
  iOS/IssueTracker/IssueTracker/LogIn/Model/ValidationChecker.swift
  iOS/IssueTracker/IssueTracker/LogIn/View/SignUp/SignUp.storyboard
  iOS/IssueTracker/IssueTracker/LogIn/View/SignUp/SignUpViewController.swift
  iOS/IssueTracker/IssueTracker/LogIn/View/SingIn/ErrorMessageLabel.swift
  iOS/IssueTracker/IssueTracker/LogIn/View/SingIn/Login.storyboard
  iOS/IssueTracker/IssueTracker/LogIn/View/SingIn/SignInViewController.swift
  iOS/IssueTracker/IssueTracker/LogIn/ViewModel/SignInViewModel.swift
  iOS/IssueTracker/IssueTracker/LogIn/ViewModel/SignUpViewModel.swift
  iOS/IssueTracker/IssueTracker/MilestoneList/MilestoneList.storyboard
  iOS/IssueTracker/IssueTracker/MilestoneList/MilestoneListViewCell.swift
  iOS/IssueTracker/IssueTracker/MilestoneList/MilestoneListViewController.swift
Labels: enhancement, iOS

#163 [BE] Release 두번째 시도
  server/build/app.js
  server/tests/autopull.html
Labels: backend

#165 [BE] fix: issue 하나 불러 올때 댓글 포함하도록 수정
  server/src/api/controllers/issue.js
  server/src/services/issue.js
  server/tests/issue.http
Labels: backend

#167 [BE] release: 오류 수정후 재배포
  server/build/app.js
Labels: backend

#170 [FE] 스토리보드 세팅 및 atom 단계에서 button과 label 생성
  client/.gitignore
  client/.storybook/main.js
  client/.storybook/preview.js
  client/package-lock.json
  client/package.json
  client/src/App.js
  client/src/HelloWorld.js
  client/src/components/atoms/Button/index.js
  client/src/components/atoms/Button/index.stories.js
  client/src/components/atoms/Label/index.js
  client/src/components/themes/default.js
  client/src/index.html
  client/src/index.js
  client/src/temp/Login.js
  client/src/temp/Title.js
Labels: chore, frontend, style

#166 [BE] 서버 배포작업 추가, 기타 오류 수정
  server/build/app.js
  server/src/services/issue.js
  server/tests/autopull.html
  server/tests/issue.http
Labels: backend

#173 [FE] Atoms 추가 (input, label, button), .gitignore 서버 추가
  client/.storybook/main.js
  client/.storybook/preview-head.html
  client/package-lock.json
  client/package.json
  client/src/components/atoms/Button/index.js
  client/src/components/atoms/Button/index.stories.js
  client/src/components/atoms/Input/index.js
  client/src/components/atoms/Input/index.stories.js
  client/src/components/atoms/Label/index.js
  client/src/components/atoms/Label/index.stories.js
  client/src/components/themes/default.js
  server/.gitignore
Labels: enhancement, frontend

#174 [Release] 마일스톤 목록 수정 반영
  client/.gitignore
  server/build/app.js
  server/src/api/routes/image.js
  server/src/api/routes/label.js
  server/src/api/routes/milestone.js
  server/src/services/milestone.js
  server/tests/auth.http
  server/tests/issue.http
  server/tests/milestone.http
Labels: backend

#175 [BE] 마일스톤 오류 수정, 테스트코드 작성
  client/.gitignore
  server/build/app.js
  server/src/api/routes/image.js
  server/src/api/routes/label.js
  server/src/api/routes/milestone.js
  server/src/services/milestone.js
  server/tests/auth.http
  server/tests/issue.http
  server/tests/milestone.http
Labels: backend

#176 [BE #04] 앱전용 github 추가
  server/build/app.js
  server/package-lock.json
  server/package.json
  server/src/api/controllers/login.js
  server/src/api/routes/login.js
  server/src/loaders/passport/apple.js
  server/src/loaders/passport/index.js
  server/src/services/github.js
  server/tests/auth.http
Labels: backend

#177 [Release] dev-back 사항 반영
  server/build/app.js
  server/package-lock.json
  server/package.json
  server/src/api/controllers/login.js
  server/src/api/routes/login.js
  server/src/loaders/passport/apple.js
  server/src/loaders/passport/index.js
  server/src/services/github.js
  server/tests/auth.http
Labels: backend

#178 [BE #56] 이슈 상세 내용 불러오기 API 수정
  server/src/models/issue.js
  server/src/models/user.js
  server/src/services/issue.js
  server/tests/issue.http
Labels: backend, refactor

#179 [BE chore] imgur 관련 configuration을 dotenv로 빼놓기
  server/.env.example
  server/src/api/routes/image.js
  server/src/config/imgur.js
Labels: backend, chore

#182 [Release] Dev-back 사항 반영
  server/.env.example
  server/build/app.js
  server/src/api/routes/image.js
  server/src/config/imgur.js
  server/src/models/issue.js
  server/src/models/user.js
  server/src/services/issue.js
  server/tests/issue.http
Labels: backend

#183 [Release] github 적용
  server/build/app.js
Labels: backend

#185 [BE #35] 이슈 목록 불러오기 API 수정
  server/src/services/issue.js
Labels: backend, refactor

#186 [release] 이슈 목록 호출 API 수정 반영
  server/src/services/issue.js
Labels: backend, refactor

#187 [iOS #57, ] issueDetail 화면 수정, API 추가, issue close, delete API 요청 추가
  iOS/IssueTracker/IssueTracker.xcodeproj/project.pbxproj
  iOS/IssueTracker/IssueTracker/Common/SceneDelegate.swift
  iOS/IssueTracker/IssueTracker/IssueDetail/Model/IssueDetailModel.swift
  iOS/IssueTracker/IssueTracker/IssueDetail/Service/IssueDetailService.swift
  iOS/IssueTracker/IssueTracker/IssueDetail/View/IssueCommentCellView.swift
  iOS/IssueTracker/IssueTracker/IssueDetail/View/IssueDetail.storyboard
  iOS/IssueTracker/IssueTracker/IssueDetail/View/IssueDetailSwipeViewController.swift
  iOS/IssueTracker/IssueTracker/IssueDetail/View/IssueDetailViewController.swift
  iOS/IssueTracker/IssueTracker/IssueDetail/ViewModel/IssueDetailViewModel.swift
  iOS/IssueTracker/IssueTracker/IssueDetailEditing/IssueDetailEditing.storyboard
  iOS/IssueTracker/IssueTracker/IssueDetailEditing/IssueDetailEditingViewController.swift
  iOS/IssueTracker/IssueTracker/IssueList/Model/IssueListModel.swift
  iOS/IssueTracker/IssueTracker/IssueList/Service/IssueListService.swift
  iOS/IssueTracker/IssueTracker/IssueList/View/Main/IssueListMainViewController.swift
  iOS/IssueTracker/IssueTracker/IssueList/View/Main/IssueResultList/IssueResultCellView.swift
  iOS/IssueTracker/IssueTracker/IssueList/View/Main/IssueResultList/IssueResultViewController.swift
  iOS/IssueTracker/IssueTracker/IssueList/ViewModel/IssueListViewModel.swift
  iOS/IssueTracker/Podfile.lock
Labels: iOS

#194 [BE fix] 누락된 데이터베이스 속성 추가 및 반영
  server/src/models/user.js
  server/src/services/issue.js
  server/src/services/user.js
Labels: backend, bug

#195 [BE] 유저 프로필 이미지 업로드 기능 추가
  server/src/api/controllers/image.js
  server/src/api/routes/image.js
  server/src/api/routes/user.js
  server/src/services/image.js
  server/src/services/milestone.js
  server/tests/milestone.http
  server/tests/user.http
Labels: backend

#196 [BE fix] issue-user 관계테이블 alias 수정하면서 생긴 오류 수정
  server/src/services/issue.js
Labels: backend, bug

#197 [BE fix] 테스트코드 수정 및 comment 관련 API에서 불필요한 매개변수 제거
  server/src/api/controllers/comment.js
  server/src/services/comment.js
  server/src/services/issue.js
  server/tests/comment.http
  server/tests/issue.http
Labels: backend, bug

#198 [release] 수정 사항 배포 서버에 반영
  server/src/api/controllers/comment.js
  server/src/api/controllers/image.js
  server/src/api/routes/image.js
  server/src/api/routes/user.js
  server/src/models/user.js
  server/src/services/comment.js
  server/src/services/image.js
  server/src/services/issue.js
  server/src/services/milestone.js
  server/src/services/user.js
  server/tests/comment.http
  server/tests/issue.http
  server/tests/milestone.http
  server/tests/user.http
Labels: backend, bug, refactor, style, test

#200 [iOS fix] 코드 프리징 후 버그 수정
  iOS/IssueTracker/IssueTracker/Common/SceneDelegate.swift
  iOS/IssueTracker/IssueTracker/IssueDetail/Model/IssueDetailModel.swift
  iOS/IssueTracker/IssueTracker/IssueDetail/Service/IssueDetailService.swift
  iOS/IssueTracker/IssueTracker/IssueDetail/View/IssueDetail.storyboard
  iOS/IssueTracker/IssueTracker/IssueDetail/View/IssueDetailViewController.swift
  iOS/IssueTracker/IssueTracker/IssueList/Model/IssueListModel.swift
  iOS/IssueTracker/IssueTracker/IssueList/Service/IssueListService.swift
  iOS/IssueTracker/IssueTracker/IssueList/View/IssueList.storyboard
  iOS/IssueTracker/IssueTracker/IssueList/View/Main/IssueListMainViewController.swift
  iOS/IssueTracker/IssueTracker/IssueList/View/Main/IssueResultList/BothSidesSwipingView.swift
  iOS/IssueTracker/IssueTracker/IssueList/View/Main/IssueResultList/IssueResultCellView.swift
  iOS/IssueTracker/IssueTracker/IssueList/ViewModel/IssueListViewModel.swift
Labels: bug, iOS

#201 [BE] 이미지 업로드 테스트코드 추가, 마일스톤 버그 픽스
  server/src/services/milestone.js
  server/tests/image.http
  server/tests/img/cat.jpg
  server/tests/img/ie_is_trash.png
  server/tests/milestone.http
Labels: backend

#218 [iOS #69] 새로운 이슈 생성 화면
  iOS/IssueTracker/IssueTracker.xcodeproj/project.pbxproj
  iOS/IssueTracker/IssueTracker/Assets.xcassets/upload.imageset/Contents.json
  iOS/IssueTracker/IssueTracker/Assets.xcassets/upload.imageset/upload.png
  iOS/IssueTracker/IssueTracker/Extenstion/UIButton.swift
  iOS/IssueTracker/IssueTracker/Extenstion/tagView.swift
  iOS/IssueTracker/IssueTracker/IssueCreation/IssueCreation.storyboard
  iOS/IssueTracker/IssueTracker/IssueCreation/IssueCreationViewController.swift
  iOS/IssueTracker/IssueTracker/IssueCreation/View/IssueCreation.storyboard
  iOS/IssueTracker/IssueTracker/IssueCreation/View/IssueCreationViewController.swift
  iOS/IssueTracker/IssueTracker/IssueDetailEditing/View/IssueDetailEditing.storyboard
  iOS/IssueTracker/IssueTracker/IssueDetailEditing/View/IssueDetailEditingViewController.swift
  iOS/IssueTracker/IssueTracker/IssueList/View/Main/IssueListMainViewController.swift
  iOS/IssueTracker/IssueTracker/LogIn/View/SingIn/SignInViewController.swift
  iOS/IssueTracker/Podfile
  iOS/IssueTracker/Podfile.lock
Labels: iOS

#210 [BE] issueFilter 기능추가, 스타일 수정
  server/build/app.js
  server/package.json
  server/src/api/controllers/comment.js
  server/src/api/controllers/image.js
  server/src/api/controllers/issue.js
  server/src/api/controllers/issueFilter.js
  server/src/api/controllers/label.js
  server/src/api/controllers/login.js
  server/src/api/controllers/milestone.js
  server/src/api/controllers/signup.js
  server/src/api/controllers/user.js
  server/src/api/index.js
  server/src/api/middlewares/comment.js
  server/src/api/middlewares/signup.js
  server/src/api/routes/issueFilter.js
  server/src/api/routes/login.js
  server/src/loaders/passport/github.js
  server/src/loaders/passport/local.js
  server/src/models/issue.js
  server/src/services/auth/apple.js
  server/src/services/auth/github.js
  server/src/services/auth/passwordBcrypt.js
  server/src/services/auth/signup.js
  server/src/services/comment.js
  server/src/services/comment/createComment.js
  server/src/services/comment/deleteComment.js
  server/src/services/comment/index.js
  server/src/services/comment/readComment.js
  server/src/services/comment/readComments.js
  server/src/services/comment/updateComment.js
  server/src/services/image/index.js
  server/src/services/image/updateProfile.js
  server/src/services/issue.js
  server/src/services/issue/createIssue.js
  server/src/services/issue/deleteIssue.js
  server/src/services/issue/index.js
  server/src/services/issue/readIssue.js
  server/src/services/issue/readIssues.js
  server/src/services/issue/updateIssue.js
  server/src/services/issueFilter.js
  server/src/services/label.js
  server/src/services/label/createLabel.js
  server/src/services/label/deleteLabel.js
  server/src/services/label/index.js
  server/src/services/label/readLabel.js
  server/src/services/label/readLabels.js
  server/src/services/label/updateLabel.js
  server/src/services/milestone.js
  server/src/services/milestone/createMilestone.js
  server/src/services/milestone/deleteMilestone.js
  server/src/services/milestone/index.js
  server/src/services/milestone/readMilestones.js
  server/src/services/milestone/updateMilestone.js
  server/src/services/passport.js
  server/src/services/searchFilter.js
  server/src/services/user/index.js
  server/src/services/user/readUsers.js
  server/tests/imgur.html
  server/tests/issue.http
  server/tests/issueFilter.http
Labels: backend

#226 [BE build] API 관련 수정 내용 반영하여 배포
  server/src/api/controllers/comment.js
  server/src/api/controllers/milestone.js
  server/src/migrations/.keep
  server/src/seeders/.keep
  server/src/services/comment/createComment.js
  server/src/services/comment/readComments.js
  server/src/services/comment/updateComment.js
  server/src/services/issue/createIssue.js
  server/src/services/issue/updateIssue.js
  server/src/services/label/createLabel.js
  server/src/services/label/updateLabel.js
  server/src/services/milestone/createMilestone.js
  server/src/services/milestone/updateMilestone.js
Labels: backend

#225 [BE fix] 빈 문자열이 request body에 들어올 경우 error 처리, comment READ API response 내용 수정
  server/build/app.js
  server/src/api/controllers/comment.js
  server/src/api/controllers/milestone.js
  server/src/config/express.js
  server/src/migrations/.keep
  server/src/seeders/.keep
  server/src/services/comment/createComment.js
  server/src/services/comment/readComments.js
  server/src/services/comment/updateComment.js
  server/src/services/issue/createIssue.js
  server/src/services/issue/readIssues.js
  server/src/services/issue/updateIssue.js
  server/src/services/label/createLabel.js
  server/src/services/label/updateLabel.js
  server/src/services/milestone/createMilestone.js
  server/src/services/milestone/updateMilestone.js
Labels: backend, bug, invalid, refactor

#228 [Release] issue Update 수정
  server/build/app.js
  server/src/services/label/updateLabel.js
Labels: backend

#229 [BE] fix: label 수정시 타이틀이 같을경우 반영안되는 오류 수정
  server/src/services/label/updateLabel.js
Labels: backend

#232 [BE fix] iOS 이슈 목록 받아오는 화면에서 필요한 속성 추가
  server/build/app.js
  server/src/services/issue/readIssues.js
Labels: backend, refactor

#233 [BE fix] iOS 이슈 목록 받아오는 화면에서 필요한 속성 추가
  server/build/app.js
  server/src/services/issue/readIssues.js
Labels: backend, refactor

#237 [Release] fix: milestone delete 버그 수정
  server/build/app.js
  server/src/services/milestone/deleteMilestone.js
Labels: backend

#238 [BE] fix: 마일스톤 Delete 수정
  server/build/app.js
  server/src/services/milestone/deleteMilestone.js
Labels: backend

#249 [BE] 댓글달린 이슈가 삭제안되던 문제 수정
  server/build/app.js
  server/src/services/issue/deleteIssue.js
Labels: backend, bug

#251 [BE] getTargetIssue 오류 수정
  server/build/app.js
  server/src/services/issue/updateIssue.js
Labels: backend, bug

#252 [Release] 수정 사항 반영
  server/build/app.js
  server/src/services/issue/updateIssue.js
Labels: backend

#253 [iOS] 이슈 상세 화면 수정 및 warning 제거
  iOS/IssueTracker/IssueTracker/Common/SceneDelegate.swift
  iOS/IssueTracker/IssueTracker/IssueCreation/Service/IssueCreationService.swift
  iOS/IssueTracker/IssueTracker/IssueDetail/View/IssueDetailEditing/Cell/MilestoneCollectionViewCell.swift
  iOS/IssueTracker/IssueTracker/IssueDetail/View/IssueDetailEditing/View/IssueDetailEditing.storyboard
  iOS/IssueTracker/IssueTracker/IssueDetail/View/IssueDetailEditing/View/IssueDetailEditingViewController.swift
  iOS/IssueTracker/IssueTracker/IssueList/Service/IssueListService.swift
  iOS/IssueTracker/IssueTracker/IssueList/View/Main/IssueResultList/IssueResultCellView.swift
  iOS/IssueTracker/IssueTracker/IssueList/View/Main/IssueResultList/IssueResultViewController.swift
  iOS/IssueTracker/IssueTracker/LabelList/View/LabelEditingViewController.swift
  iOS/IssueTracker/IssueTracker/LabelList/View/LabelListViewController.swift
  iOS/IssueTracker/IssueTracker/LogIn/Model/ValidationChecker.swift
  iOS/IssueTracker/IssueTracker/LogIn/Service/LoginManager.swift
  iOS/IssueTracker/IssueTracker/LogIn/View/SignUp/SignUpViewController.swift
  iOS/IssueTracker/IssueTracker/LogIn/View/SingIn/SignInViewController.swift
  iOS/IssueTracker/IssueTracker/MilestoneList/View/MilestoneEditingViewController.swift
  iOS/IssueTracker/IssueTracker/MilestoneList/View/MilestoneListViewCell.swift
  iOS/IssueTracker/IssueTracker/MilestoneList/View/MilestoneListViewController.swift
Labels: iOS

#257 [BE] 배포
  server/build/app.js
  server/src/api/controllers/login.js
  server/src/services/auth/apple.js
Labels: backend

#261 [Release] axios 토큰 받아오도록 수정
  client/build/bundle.js
  client/src/components/molecules/IssueListTitle/IssueListTitle.js
  client/src/components/molecules/MilestoneInform/MilestoneInform.js
  client/src/components/organisms/IssueCreate/IssueCreate.js
  client/src/constants/issue/issueCreate.js
  client/src/constants/milestone/MilestoneInform.js
  client/src/pages/IssueCreate.js
  client/src/system/axios/config.js
Labels: frontend
